4drafts/Models/Categories/CategoriesBrowseModel.cs
using _4drafts.Models.Threads;

namespace _4drafts.Models.Categories
{
    public class CategoriesBrowseModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int ThreadCount { get; set; }

        public ThreadViewModel LastEntry { get; set; }
    }
}

4drafts/Models/Categories/CategoryBrowseModel.cs
using System.Collections.Generic;
using _4drafts.Models.Threads;

namespace _4drafts.Models.Categories
{
    public class CategoryBrowseModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public List<ThreadsBrowseModel> Threads { get; init; }
    }
}

4drafts/Controllers/CategoriesController.cs
using _4drafts.Data;
using _4drafts.Models.Categories;
using _4drafts.Services;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using _4drafts.Models.Threads;
using Microsoft.EntityFrameworkCore;

namespace _4drafts.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly ITimeWarper timeWarper;
        private readonly _4draftsDbContext data;
        public CategoriesController(ITimeWarper timeWarper,
            _4draftsDbContext data)
        {
            this.timeWarper = timeWarper;
            this.data = data;
        }

        public IActionResult All()
        {
            var categories = this.data.Categories
                .Select(c => new CategoriesBrowseModel
                {
                    Id = c.Id,
                    Name = c.Name,
                    Description = c.Description,
                    ThreadCount = this.data.Threads.Count(t => t.CategoryId == c.Id),
                    LastEntry = GetLastThreadInCategory(c.Id, this.data, this.timeWarper)
                })
                .OrderByDescending(c => c.ThreadCount)
                .ToList();

            return View(categories);
        }

        public IActionResult Browse(int categoryId)
        {
            if (!this.data.Categories.Any(c => c.Id == categoryId)) return NotFound();

            var name = this.data.Categories.FirstOrDefault(c => c.Id == categoryId).Name;
            var desc = this.data.Categories.FirstOrDefault(c => c.Id == categoryId).Description;

            var threads = this.data.Threads
                .Include(t => t.Category)
                .Where(t => t.CategoryId == categoryId)
                .OrderByDescending(t => t.CreatedOn)
                .Select(t => new ThreadsBrowseModel
                {
                    Id = t.Id,
                    Title = t.Title,
                    Description = t.Description,
                    CategoryId = t.CategoryId,
                    CreatedOn = this.timeWarper.TimeAgo(t.CreatedOn),
                    Points = t.Points,
                    AuthorId = t.AuthorId,
                    AuthorName = t.Author.UserName,
                    AuthorAvatarUrl = t.Author.AvatarUrl,
                    CommentCount = ThreadCommentCount(t.Id, this.data),
                })
                .ToList();

            return View(new CategoryBrowseModel 
            { 
                Id = categoryId,
                Name = name,
                Description = desc,
                Threads = threads,
            });
        }

        //Functions
        private static ThreadViewModel GetLastThreadInCategory(int categoryId, 
            _4draftsDbContext data, 
            ITimeWarper timeWarper)
        {
            var thread = data.Threads
                .Include(t => t.Author)
                .Where(t => t.CategoryId == categoryId)
                .OrderByDescending(t => t.CreatedOn)
                .FirstOrDefault();

            var result = thread == null ? null : new ThreadViewModel
            {
                Id = thread.Id,
                Title = thread.Title,
                CreatedOn = timeWarper.TimeAgo(thread.CreatedOn),
                AuthorId = thread.AuthorId,
                AuthorName = thread.Author.UserName,
                AuthorAvatarUrl = thread.Author.AvatarUrl
            };

            return result;
        }

        private static int ThreadCommentCount(string threadId, 
            _4draftsDbContext data) 
            => data.Comments.Count(c => c.ThreadId == threadId);
    }
}

4drafts/Controllers/ThreadsController.cs
using _4drafts.Data;
using _4drafts.Data.Models;
using _4drafts.Models.Genres;
using _4drafts.Models.Comments;
using _4drafts.Models.Drafts;
using _4drafts.Models.Shared;
using _4drafts.Models.Threads;
using _4drafts.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using static _4drafts.Services.ControllerExtensions;
using static _4drafts.Data.DataConstants;

namespace _4drafts.Controllers
{
    public class ThreadsController : Controller
    {
        private readonly ITimeWarper timeWarper;
        private readonly _4draftsDbContext data;
        private readonly UserManager<User> userManager;
        public ThreadsController(ITimeWarper timeWarper,
            _4draftsDbContext data,
            UserManager<User> userManager)
        {
            this.timeWarper = timeWarper;
            this.data = data;
            this.userManager = userManager;
        }

        [HttpGet]
        public async Task<IActionResult> Read(string t)
        {
            var thread = this.data.Threads
                .Include(x => x.Author)
                .Include(x => x.GenreThreads)
                .Include(x => x.ThreadType)
                .Include("Comments.Author")
                .FirstOrDefault(x => x.Id == t);

            if (thread == null) return NotFound();

            var author = await this.userManager.FindByIdAsync(thread.AuthorId);

            if (author == null) return NotFound();

            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);

            var liked = this.data
                .UserThreads.Any(ut => ut.UserId == userId && ut.ThreadId == t);

            var threadCount = UserThreadCount(thread.AuthorId, this.data);

            var threadResult = new ThreadViewModel
            {
                Id = thread.Id,
                Title = thread.Title,
                TypeId = thread.ThreadTypeId,
                Type = thread.ThreadType.Name,
                Content = thread.Content,
                CreatedOn = this.timeWarper.TimeAgo(thread.CreatedOn),
                AuthorId = author.Id,
                AuthorName = author.UserName,
                AuthorAvatarUrl = author.AvatarUrl,
                AuthorRegisteredOn = author.RegisteredOn.ToString("MMMM yyyy", CultureInfo.InvariantCulture),
                AuthorThreadCount = threadCount,
                Points = thread.Points,
                Liked = liked,
                GenreIds = thread.GenreThreads.Select(gt => gt.GenreId),
                Comments = thread.Comments
                .OrderByDescending(t => t.AuthorId == userId)
                .ThenByDescending(t => t.Points)
                .Select(c => new CommentViewModel
                {
                    Id = c.Id,
                    Content = c.Content,
                    Points = c.Points,
                    Liked = CommentIsLiked(c.Id, userId, this.data),
                    CreatedOn = timeWarper.TimeAgo(c.CreatedOn),
                    AuthorId = c.AuthorId,
                    AuthorName = c.Author.UserName,
                    AuthorAvatarUrl = c.Author.AvatarUrl,
                    AuthorRegisteredOn = c.Author.RegisteredOn.ToString("MMMM yyyy", CultureInfo.InvariantCulture),
                    AuthorCommentCount = UserCommentCount(c.AuthorId, this.data),
                    ThreadId = c.ThreadId
                })
                .ToList()
            };

            return View(threadResult);
        }

        [HttpGet]
        public async Task<IActionResult> Browse(int genre = 0, int type = 0, string sort = "best", int page = 1, string u = null, bool liked = false)
        {
            var threads = new List<ThreadsBrowseModel>();

            var user = await this.userManager.GetUserAsync(this.User);

            if (genre == 0 && type == 0)
            {
                switch (sort)
                {
                    case "controversial":
                        {
                            threads = this.data.Threads
                            .Include(t => t.Comments)
                            .Include(t => t.GenreThreads)
                            .Include(t => t.ThreadType)
                            .OrderByDescending(t => t.Comments.Count)
                            .Select(t => new ThreadsBrowseModel
                            {
                                Id = t.Id,
                                Title = t.Title,
                                ThreadTypeId = t.ThreadTypeId,
                                ThreadTypeName = t.ThreadType.Name,
                                Content = t.Content,
                                Genres = GetGenres(this.data, 0, t.Id),
                                CreatedOn = this.timeWarper.TimeAgo(t.CreatedOn),
                                FullDate = this.timeWarper.FullDate(t.CreatedOn),
                                Points = t.Points,
                                AuthorId = t.AuthorId,
                                AuthorName = t.Author.UserName,
                                AuthorAvatarUrl = t.Author.AvatarUrl,
                                CommentCount = ThreadCommentCount(t.Id, this.data),
                            }).ToList();
                            break;
                        }
                    case "best":
                        {
                            threads = this.data.Threads
                            .Include(t => t.Comments)
                            .Include(t => t.GenreThreads)
                            .Include(t => t.ThreadType)
                            .OrderByDescending(t => t.Points)
                            .ThenByDescending(t => t.Comments.Count)
                            .Select(t => new ThreadsBrowseModel
                            {
                                Id = t.Id,
                                Title = t.Title,
                                ThreadTypeId = t.ThreadTypeId,
                                ThreadTypeName = t.ThreadType.Name,
                                Content = t.Content,
                                Genres = GetGenres(this.data, 0, t.Id),
                                CreatedOn = this.timeWarper.TimeAgo(t.CreatedOn),
                                FullDate = this.timeWarper.FullDate(t.CreatedOn),
                                Points = t.Points,
                                AuthorId = t.AuthorId,
                                AuthorName = t.Author.UserName,
                                AuthorAvatarUrl = t.Author.AvatarUrl,
                                CommentCount = ThreadCommentCount(t.Id, this.data),
                            }).ToList();
                            break;
                        }
                    case "new":
                        {
                            threads = this.data.Threads
                            .Include(t => t.Comments)
                            .Include(t => t.GenreThreads)
                            .Include(t => t.ThreadType)
                            .OrderByDescending(t => t.CreatedOn)
                            .Select(t => new ThreadsBrowseModel
                            {
                                Id = t.Id,
                                Title = t.Title,
                                ThreadTypeId = t.ThreadTypeId,
                                Content = t.Content,
                                ThreadTypeName = t.ThreadType.Name,
                                Genres = GetGenres(this.data, 0, t.Id),
                                CreatedOn = this.timeWarper.TimeAgo(t.CreatedOn),
                                FullDate = this.timeWarper.FullDate(t.CreatedOn),
                                Points = t.Points,
                                AuthorId = t.AuthorId,
                                AuthorName = t.Author.UserName,
                                AuthorAvatarUrl = t.Author.AvatarUrl,
                                CommentCount = ThreadCommentCount(t.Id, this.data),
                            }).ToList();
                            break;
                        }
                    default:
                        {
                            threads = this.data.Threads
                            .Include(t => t.Comments)
                            .Include(t => t.GenreThreads)
                            .Include(t => t.ThreadType)
                            .Select(t => new ThreadsBrowseModel
                            {
                                Id = t.Id,
                                Title = t.Title,
                                ThreadTypeId = t.ThreadTypeId,
                                ThreadTypeName = t.ThreadType.Name,
                                Content = t.Content,
                                Genres = GetGenres(this.data, 0, t.Id),
                                CreatedOn = this.timeWarper.TimeAgo(t.CreatedOn),
                                FullDate = this.timeWarper.FullDate(t.CreatedOn),
                                Points = t.Points,
                                AuthorId = t.AuthorId,
                                AuthorName = t.Author.UserName,
                                AuthorAvatarUrl = t.Author.AvatarUrl,
                                CommentCount = ThreadCommentCount(t.Id, this.data),
                            }).ToList();
                            break;
                        }
                }
            }
            else if(genre != 0 && type == 0)
            {
                switch (sort)
                {
                    case "controversial":
                        {
                            threads = this.data.Threads
                            .Include(t => t.Comments)

4drafts/Views/Categories/All.cshtml
@model List<CategoriesBrowseModel>
@{
    ViewBag.Title = "Categories";
}
<div class="container-fluid mt-5 mb-4">
    <div class="row">
        <div class="col-md-12">
            <div class="card border mb-3">
                <div class="card-header pr-0 pl-0">
                    <div class="row no-gutters align-items-center w-100">
                        <div class="col font-weight-bold pl-3">[Genre]</div>
                        <div class="d-none d-md-block col-6">
                            <div class="row no-gutters align-items-center">
                                <div class="col-3 font-weight-bold">[Threads]</div>
                                <div class="col-6 ml-5 font-weight-bold">[Last entry]</div>
                            </div>
                        </div>
                    </div>
                </div>
                @{
                    foreach (var category in Model)
                    {
                        <div class="card-body py-3">
                            <div class="row no-gutters align-items-center">
                                <div class="col">
                                    <a asp-controller="Categories" asp-action="Browse" asp-route-categoryId="@category.Id" class="text-big font-weight-semibold" data-abc="true">
                                        @category.Name
                                    </a>
                                </div>
                                <div class="tooltip mr-350 hide-sm zoom">
                                    <a onclick="categoryInfo(@category.Id)"><i class="info-circle fas fa-info-circle"></i></a>
                                    <span class="tooltiptext">@category.Description</span>
                                </div>
                                <div class="d-none d-md-block col-6">
                                    <div class="row no-gutters align-items-center">
                                        <div class="col-3 ml-2">@category.ThreadCount</div>
                                        @{ if (category.LastEntry != null)
                                            {
                                                var avatar = "";
                                                if (!String.IsNullOrWhiteSpace(category.LastEntry.AuthorAvatarUrl)) avatar = category.LastEntry.AuthorAvatarUrl;
                                                else avatar = "https://image.flaticon.com/icons/png/512/64/64572.png";
                                                <div class="media col-6 ml-5 align-items-center media-img-40">
                                                    <img src="@avatar" class="d-block ui-w-30 rounded-circle border">
                                                    <div class="media-body flex-truncate ml-2">
                                                        <a asp-controller="Threads" asp-action="Read" asp-route-threadId="@category.LastEntry.Id" class="d-block text-truncate">@category.LastEntry.Title</a>
                                                        <div class="text-muted small text-truncate">@category.LastEntry.CreatedOn &nbsp;·&nbsp; <a onclick="viewProfile('@category.LastEntry.AuthorId')" class="text-muted">@category.LastEntry.AuthorName</a></div>
                                                    </div>
                                                </div>
                                            }
                                            else
                                            {
                                                <div class="media col-6 ml-5 align-items-center">
                                                    <img src="https://image.flaticon.com/icons/png/512/42/42901.png" class="d-block ui-w-30 rounded-circle" />
                                                    <div class="media-body flex-truncate ml-2">
                                                        Such empty...
                                                    </div>
                                                </div>
                                            }
                                        }
                                    </div>
                                </div>
                            </div>
                        </div>
                     <hr class="m-0">
                    }
                }
            </div>
        </div>
    </div>
</div>

4drafts/Views/Categories/Browse.cshtml
@model CategoryBrowseModel
@{
    ViewBag.Title = Model.Name;
    var user = await this.userManager.GetUserAsync(User);
    var categoryId = Model.Id;
}

<div class="container-fluid">
    <div class="jumbotron">
        <h1 class="display-3 strokeme">@Model.Name</h1>
        <p class="lead">@Model.Description</p>
    </div>
    <div class="container-fluid" id="threads-section">
        <partial name="_ThreadsPartial" model="@Model.Threads" />
    </div>
</div>